/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

//import entidades.Pedido;
import accesoADatos.ProductoData;
import entidades.Producto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import accesoADatos.MesaData;
import accesoADatos.PedidoData;
import accesoADatos.PedidoProductoData;
import entidades.Pedido;
import javax.swing.JOptionPane;



public class VistaPagos extends javax.swing.JFrame {
    
     private DefaultTableModel modelo = new DefaultTableModel();
    private ArrayList<Object> pedidoproducto;
    private String estado;
     Producto pp = new Producto();
     ProductoData pd = new ProductoData();
      Date fechaActual = new Date();
    String fechaFormato = new SimpleDateFormat("yyyy-MM-dd").format(fechaActual);
     double Totalpagar = 00000.00;
     PedidoProductoData ppd = new PedidoProductoData();
     
    /**
     * Creates new form VistaPagos
     */
    public VistaPagos() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        armarCabecera();
         modelo = new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        
        jTFactura.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFactura = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTFechaHora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBVolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLTotalpg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTSubtotal = new javax.swing.JTable();
        jBMesa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        jTFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plato", "Cant", "Precio"
            }
        ));
        jTFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFacturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTFactura);

        jLabel1.setText("Fecha y Hora:");

        jTFechaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFechaHoraActionPerformed(evt);
            }
        });

        jLabel4.setText("Total a pagar:");

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 153, 153));
        jLabel6.setText("Finalizar Pedido");

        jLTotalpg.setText("00.00");
        jLTotalpg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLTotalpgMouseClicked(evt);
            }
        });

        jTSubtotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subtotal"
            }
        ));
        jTSubtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTSubtotalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTSubtotal);

        jBMesa.setText("Ingrese Mesa");
        jBMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jTFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLTotalpg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBVolver))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jBMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBMesa)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(306, 337, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addComponent(jLTotalpg))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap())
                    .addComponent(jBVolver, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/resto pagos.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        // TODO add your handling code here:
  
          Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
               
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jTFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFacturaMouseClicked
        // TODO add your handling code here:
    

        this.pedidoproducto = new ArrayList<>();
       this.estado = "libre";
        Object pedido = null;
           this.pedidoproducto.add(pedido);
           this.pedidoproducto.remove(pedido);
      
        Object PedidoProducto = null;
        this.pedidoproducto.add(pedido);
      
    

    
       
    
    }//GEN-LAST:event_jTFacturaMouseClicked

    private void jLTotalpgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTotalpgMouseClicked
        // TODO add your handling code here:
//    
//        public List<Producto> listar() {
//        return this.productos;
//        double Totalpagar = 0.00;
//        int numFila = jTFactura.getRowCount();
//        for (int i = 0; i < numFila; i++) {
//            double cal = Double.parseDouble(String.valueOf(jTFactura.getModel().getValueAt(i, 4)));
//            Totalpagar += cal;
//        }
//        jLTotalpg.setText(String.format("%.2f", Totalpagar));
        
    }//GEN-LAST:event_jLTotalpgMouseClicked

    private void jTFechaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFechaHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFechaHoraActionPerformed

    private void jTSubtotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTSubtotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSubtotalMouseClicked

    private void jBMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMesaActionPerformed
        // TODO add your handling code here:
        limpiarFilas();
        
            int mesa= Integer.parseInt(JOptionPane.showInputDialog("Ingrese numero de mesa a buscar: "));
          for(Pedido p: ppd.listarPedidoMesa(mesa)){
                modelo.addRow(new Object[]{p.getIdMesa(),p.getNombreMesero(),p.getImporte(),p.isCobrada()});
            }
    }//GEN-LAST:event_jBMesaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPagos().setVisible(true);
            }
        });
    }
//        private void TotalPagar(JTable tabla, JLabel label) {
//        double Totalpagar = 0.00;
//        int numFila = tabla.getRowCount();
//        for (int i = 0; i < numFila; i++) {
//            double cal = Double.parseDouble(String.valueOf(tabla.getModel().getValueAt(i, 4)));
//            Totalpagar += cal;
//        }
//        label.setText(String.format("%.2f", Totalpagar));
//    }
//            public void verProducto(int id_producto) {
//                Producto produ = new Producto();
//               
//        
//        jBVolver.setText("" + produ.getNombre());
//        jTFechaHora.setText("" + ());
////        jTMesa.setText("" + produ.getPrecio());
//        jLTotalpg.setText(estado);
//
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBMesa;
    private javax.swing.JButton jBVolver;
    private javax.swing.JLabel jLTotalpg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTFactura;
    private javax.swing.JTextField jTFechaHora;
    private javax.swing.JTable jTSubtotal;
    // End of variables declaration//GEN-END:variables
public void armarCabecera(){
   ArrayList<Object>titulo = new ArrayList();
// titulo.add("ID");
 titulo.add("producto");
 titulo.add("cantidad");
 titulo.add("precio");
 

 for(Object tit:titulo){
 modelo.addColumn(tit);
 }
 jTFactura.setModel(modelo);


}

private void limpiarFilas(){
  int filas=jTFactura.getRowCount()-1;
  for(;filas>=0;filas--){
  modelo.removeRow(filas);
  }

}

   private void llenarTabla() {
       limpiarFilas();
    
            for(Producto p:pd.listarProductoFi()){
               modelo.addRow(new Object[]{pp.getNombre(),pp.getCantidad(),pp.getPrecio()});

            }
    }
}





